export PYTHONPATH=$PYTHONPATH:$PWD

# pass
export API_KEY="Bearer xxxx" # 大模型的api key
export BASE_URL="xxx" # 大模型的base url
export AMAP_MAPS_API_KEY="xxx" # 高德地图API密钥#高德的api key

# 微服务
export REJECT_URL="http://127.0.0.1:8007/reject-server/v1"
export INTENT_URL="http://127.0.0.1:8008/intent-server/v1"
export NLU_URL="http://127.0.0.1:8009/chatnlu-server/v1"
export ENTRY_URL="http://127.0.0.1:8080/request_nlu"
